<?php
declare(strict_types=1);

namespace App\Console\Commands;

use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\InputInterface;
use Laventure\Component\Console\Output\OutputInterface;


/**
 * AppUsersDumpCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 12/03/2024 15:22:09>
*/
class AppUsersDumpCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'app:users:dump';



    /**
     * @var array
    */
    protected array $description = [
       "app:users:dump description ..."
    ];





    /**
     * @inheritDoc
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        // put your logic here

        $output->success("You are ready for execution <app:users:dump>");

        return Command::SUCCESS;
    }
}