<?php
declare(strict_types=1);

namespace App\Console\Commands;

use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\InputInterface;
use Laventure\Component\Console\Output\OutputInterface;


/**
 * FooCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 12/03/2024 12:54:19>
*/
class FooCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'foo';



    /**
     * @var array
    */
    protected array $description = [
       "foo description ..."
    ];





    /**
     * @inheritDoc
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        // put your logic here

        $output->success("You are ready for execution <foo>");

        return Command::SUCCESS;
    }
}