<?php
declare(strict_types=1);

namespace App\Console\Commands;

use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\InputInterface;
use Laventure\Component\Console\Output\OutputInterface;


/**
 * TestCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 12/03/2024 05:23:35>
*/
class TestCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'test';



    /**
     * @var array
    */
    protected array $description = [];





    /**
     * @inheritDoc
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        // put your logic here

        $output->success("You are ready for execution <test>");

        return Command::SUCCESS;
    }
}