<?php
namespace App\Http\Controllers\Api\Books;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Http\Message\Response\JsonResponse;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * BookController
 *
 * @package App\Http\Controllers\Api\Books
 *
 * <Generated By Laventure 14/03/2024 12:57:13>
*/
class BookController extends AbstractController
{
        


        #[Route('/api/books/book', methods: ['GET|HEAD'], name: 'api.books.book.index')]
        public function index(Request $request): JsonResponse
        {
               // TODO some logic here
        }


        #[Route('/api/books/book/{id}', methods: ['GET'], name: 'api.books.book.show')]
        public function show(Request $request): JsonResponse
        {
               // TODO some logic here
        }


        #[Route('/api/books/book', methods: ['POST'], name: 'api.books.book.store')]
        public function store(Request $request): JsonResponse
        {
               // TODO some logic here
        }


        #[Route('/api/books/book/{id}', methods: ['PUT|PATCH'], name: 'api.books.book.update')]
        public function update(Request $request): JsonResponse
        {
               // TODO some logic here
        }


        #[Route('/api/books/book/{id}', methods: ['DELETE'], name: 'api.books.book.destroy')]
        public function destroy(Request $request): JsonResponse
        {
               // TODO some logic here
        }
}