<?php
declare(strict_types=1);

namespace App\ORM\Persistence\Entity\Books;


/**
 * Book
 *
 * @package  App\ORM\Persistence\Entity\Books
 *
 * <Generated By Laventure 13/03/2024 05:47:36>
*/
class Book
{

}