<?php
namespace App\Http\Controllers\Api\v2;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * UserController
 *
 * @package App\Http\Controllers\Api\v2
 *
 * <Generated By Laventure 13/03/2024 07:35:12>
*/
class UserController extends AbstractController
{

         

        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
              return new Response("UserController::index");
        }
}