<?php
declare(strict_types=1);

namespace App\ORM\Persistence\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Column\Column;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240402083230
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\Persistence\Migrations
 *
 * <Generated By Laventure 02/04/2024 08:32:30>
*/
class Version20240402083230 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->update('users', function (Blueprint $table) {
               $table->string('profession')->nullable();
               $table->text('address')->nullable();
               $table->modifyColumn('email', function (Column $column) {
                   return $column->string(150)->unique();
               });
               $table->modifyColumn('username', function (Column $column) {
                   return $column->string(100)->unique();
               });
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
           $schema->drop('users');
    }
}