<?php
declare(strict_types=1);

namespace App\ORM\Mapping\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240326193450
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\Mapper\Migrations
 *
 * <Generated By Laventure 26/03/2024 19:34:50>
*/
class Version20240326193450 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->create('products', function (Blueprint $table) {
               $table->id();
               $table->string('name');
               $table->boolean('in_stock')->default(0);
               $table->float('price');
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
           $schema->drop('products');
    }
}