<?php
declare(strict_types=1);

namespace App\ORM\Mapping\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240401192936
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\Mapping\Migrations
 *
 * <Generated By Laventure 01/04/2024 19:29:36>
*/
class Version20240401192936 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->create('foo', function (Blueprint $table) {
               $table->id();
               // ...
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
           $schema->drop('foo');
    }
}