<?php
declare(strict_types=1);

namespace App\ORM\DataMapper\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240326193945
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\DataMapper\Migrations
 *
 * <Generated By Laventure 26/03/2024 19:39:45>
*/
class Version20240326193945 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->create('cart_item', function (Blueprint $table) {
               $table->id();
               $table->integer('quantity')->default(0);
               $table->float('price');
               $table->bigInteger('product_id');
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
        $schema->drop('cart_item');
    }
}