<?php
declare(strict_types=1);

namespace App\ORM\DataMapper\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Constraints\Contract\ForeignKeyInterface;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240326021826
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\DataMapper\Migrations
 *
 * <Generated By Laventure 26/03/2024 02:18:26>
*/
class Version20240326021826 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->create('goods', function (Blueprint $table) {
               $table->id();
               $table->string('title', 200);
               $table->string('slug', 300);
               $table->text('description');
               $table->float('price');
               $table->string('image', 200);
               $table->boolean('in_stock')->default(0);
               $table->nullableTimestamps();
               $table->softDeletes();
               $table->bigInteger('user_id');
               $table->foreign('user_id', function (ForeignKeyInterface $foreign) {
                   return $foreign->references('id')->on('users')->onDelete();
               });
               /*
               $table->foreign('user_id')
                   ->references('id')
                   ->on('users')
                   ->onDelete('cascade');
               */
               $table->unique(['slug']);
               $table->index(['title']);
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
         $schema->drop('goods');
    }
}