<?php
declare(strict_types=1);

namespace App\ORM\DataMapper\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240326000042
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\DataMapper\Migrations
 *
 * <Generated By Laventure 26/03/2024 00:00:42>
*/
class Version20240326000042 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
           $schema->create('users', function (Blueprint $table) {
               $table->id();
               $table->string('username', 150);
               $table->string('email', 180);
               $table->string('password', 230);
               $table->boolean('active')->default(0);
               $table->timestamps();
               $table->softDeletes();
               $table->unique(['email']);
           });
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
          $schema->drop('users');
    }
}