<?php
declare(strict_types=1);

namespace App\ORM\Persistence\Fixtures;

use Laventure\Component\Database\ORM\Manager\Contract\EntityManagerInterface;
use Laventure\Component\Database\ORM\Manager\Fixtures\Fixture;


/**
 * FooFixture
 *
 * @package  App\ORM\Persistence\Fixtures
 *
 * <Generated By Laventure 02/04/2024 19:11:45>
*/
class FooFixture extends Fixture
{

      /**
       * @inheritDoc
      */
      public function load(EntityManagerInterface $em): void
      {
           /*
            $foo = new Foo();
            $foo->setSomething('added some data');
            ...
            $em->persist($foo);
            $em->flush();
           */
      }
}