<?php
declare(strict_types=1);

namespace App\Console\Commands\Demo;

use App\Generator\Demo\DemoClassGenerator;
use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\InputInterface;
use Laventure\Component\Console\Output\OutputInterface;


/**
 * DemoCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 14/03/2024 02:08:20>
*/
class DemoCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'demo';



    /**
     * @var array
    */
    protected array $description = [
       "demo description ..."
    ];



    public function __construct(
        protected DemoClassGenerator $defaultClassGenerator
    )
    {
        parent::__construct($this->name);
    }





    /**
     * @inheritDoc
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        // put your logic here
        dump(get_class($this->defaultClassGenerator));

        $output->success("You are ready for execution <demo>");

        return Command::SUCCESS;
    }
}