<?php
declare(strict_types=1);

namespace App\ORM\Mapper\Migrations;

use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;

/**
 * Version20240314155029
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\Mapper\Migrations
 *
 * <Generated By Laventure 14/03/2024 15:50:29>
*/
class Version20240314155029 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
         /*
           $schema->create('foo', function (Blueprint $table) {
               $table->increments('id');
               // ...
           });
         */
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
         /*
           $schema->dropIfExists('foo');
         */
    }
}