<?php
declare(strict_types=1);

namespace App\ORM\Mapper\Migrations;

use Laventure\Component\Database\Schema\Blueprint\Blueprint;
use Laventure\Component\Database\Schema\Migration\Migration;
use Laventure\Component\Database\Schema\SchemaInterface;


/**
 * Version20240314193414
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @package  App\ORM\Mapper\Migrations
 *
 * <Generated By Laventure 14/03/2024 19:34:14>
*/
class Version20240314193414 extends Migration
{

    /**
     * @inheritDoc
    */
    public function up(SchemaInterface $schema): void
    {
        $schema->create('products', function (Blueprint $table) {
            $table->integer('id')->primary()->increment();
            $table->string('name');
            $table->boolean('test')->default(0);
            $table->float('price');
        });


        /*
        $qb = $schema->getConnection()->createQueryBuilder();

        $qb->insert('products')
            ->values([
                [
                    'name'  => 'Tourelle de Defense',
                    'price' => 150.20
                ],
                [
                    'name'  => 'Tourelle de niveau 3',
                    'price' => 125
                ]
            ])
            ->getQuery()->execute();
        */
    }




    /**
     * @inheritDoc
    */
    public function down(SchemaInterface $schema): void
    {
        $schema->dropIfExists('products');
    }
}