<?php
namespace App\Http\Controllers;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * BarController
 *
 * @package App\Http\Controllers
 *
 * <Generated By Laventure 12/03/2024 17:10:07>
*/
class BarController extends AbstractController
{

         
}