<?php
namespace App\Http\Controllers;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Http\Message\Response\JsonResponse;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * BookController
 *
 * @package App\Http\Controllers
 *
 * <Generated By Laventure 14/03/2024 12:33:46>
*/
class BookController extends AbstractController
{

        #[Route('/book', methods: ['GET|HEAD'], name: 'book.index')]
        public function index(Request $request): Response
        {
             return new Response('hello');
        }


        #[Route('/book/{id}', methods: ['GET'], name: 'book.show')]
        public function show(Request $request): Response
        {

        }


        #[Route('/book/create', methods: ['GET'], name: 'book.create')]
        public function create(Request $request): Response
        {

        }


        #[Route('/book/store', methods: ['POST'], name: 'book.store')]
        public function store(Request $request): Response
        {

        }


        #[Route('/book/{id}/edit', methods: ['GET'], name: 'book.edit')]
        public function edit(Request $request): Response
        {

        }


        #[Route('/book/{id}', methods: ['PUT|PATCH'], name: 'book.update')]
        public function update(Request $request): Response
        {

        }


        #[Route('/book/{id}', methods: ['DELETE'], name: 'book.destroy')]
        public function destroy(Request $request): Response
        {

        }
}