<?php
namespace App\Http\Controllers;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * CreateUserController
 *
 * @package App\Http\Controllers
 *
 * <Generated By Laventure 12/03/2024 18:51:27>
*/
class CreateUserController extends AbstractController
{

         

        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
              return new Response("CreateUserController::index");
        }
}