<?php
namespace App\Http\Controllers;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * FooController
 *
 * @package App\Http\Controllers
 *
 * <Generated By Laventure 12/03/2024 15:06:04>
*/
class FooController extends AbstractController
{

         
}