<?php
declare(strict_types=1);

namespace App\Console\Commands\User;

use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\InputInterface;
use Laventure\Component\Console\Output\OutputInterface;


/**
 * CreateUserCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 13/03/2024 06:46:01>
*/
class CreateUserCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'app:make:user';



    /**
     * @var array
    */
    protected array $description = [
       "app:make:user description ..."
    ];





    /**
     * @inheritDoc
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        // put your logic here

        $output->success("You are ready for execution <app:make:user>");

        return Command::SUCCESS;
    }
}