<?php
namespace App\Http\Controllers\Books;


use Laventure\Component\Http\Message\Response\Response;
use Laventure\Component\Routing\Route\Attributes\Route;
use Laventure\Foundation\Http\Controller\AbstractController;
use Laventure\Foundation\Http\Message\Request\Request;


/**
 * BookController
 *
 * @package App\Http\Controllers\Books
 *
 * <Generated By Laventure 12/03/2024 17:10:29>
*/
class BookController extends AbstractController
{

         
}