<?php
declare(strict_types=1);

namespace App\ORM\Mapper\Entity;


/**
 * SomeEntity
 *
 * @package  App\ORM\Persistence\Entity
 *
 * <Generated By Laventure 14/03/2024 15:55:15>
*/
class SomeEntity
{

}